
  create table "public"."WorkoutPlan" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text,
    "user_id" bigint
      );


alter table "public"."WorkoutPlan" enable row level security;

alter table "public"."users" add column "email" text not null;

alter table "public"."users" add column "gender" text;

alter table "public"."users" add column "password" text not null;

alter table "public"."users" add column "weight" integer;

CREATE UNIQUE INDEX "WorkoutPlan_pkey" ON public."WorkoutPlan" USING btree (id);

CREATE UNIQUE INDEX users_password_key ON public.users USING btree (password);

alter table "public"."WorkoutPlan" add constraint "WorkoutPlan_pkey" PRIMARY KEY using index "WorkoutPlan_pkey";

alter table "public"."WorkoutPlan" add constraint "WorkoutPlan_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) not valid;

alter table "public"."WorkoutPlan" validate constraint "WorkoutPlan_user_id_fkey";

alter table "public"."users" add constraint "users_gender_check" CHECK ((gender = ANY (ARRAY['male'::text, 'female'::text, 'other'::text]))) not valid;

alter table "public"."users" validate constraint "users_gender_check";

alter table "public"."users" add constraint "users_password_key" UNIQUE using index "users_password_key";

grant delete on table "public"."WorkoutPlan" to "anon";

grant insert on table "public"."WorkoutPlan" to "anon";

grant references on table "public"."WorkoutPlan" to "anon";

grant select on table "public"."WorkoutPlan" to "anon";

grant trigger on table "public"."WorkoutPlan" to "anon";

grant truncate on table "public"."WorkoutPlan" to "anon";

grant update on table "public"."WorkoutPlan" to "anon";

grant delete on table "public"."WorkoutPlan" to "authenticated";

grant insert on table "public"."WorkoutPlan" to "authenticated";

grant references on table "public"."WorkoutPlan" to "authenticated";

grant select on table "public"."WorkoutPlan" to "authenticated";

grant trigger on table "public"."WorkoutPlan" to "authenticated";

grant truncate on table "public"."WorkoutPlan" to "authenticated";

grant update on table "public"."WorkoutPlan" to "authenticated";

grant delete on table "public"."WorkoutPlan" to "service_role";

grant insert on table "public"."WorkoutPlan" to "service_role";

grant references on table "public"."WorkoutPlan" to "service_role";

grant select on table "public"."WorkoutPlan" to "service_role";

grant trigger on table "public"."WorkoutPlan" to "service_role";

grant truncate on table "public"."WorkoutPlan" to "service_role";

grant update on table "public"."WorkoutPlan" to "service_role";


