revoke delete on table "public"."WorkoutPlan" from "anon";

revoke insert on table "public"."WorkoutPlan" from "anon";

revoke references on table "public"."WorkoutPlan" from "anon";

revoke select on table "public"."WorkoutPlan" from "anon";

revoke trigger on table "public"."WorkoutPlan" from "anon";

revoke truncate on table "public"."WorkoutPlan" from "anon";

revoke update on table "public"."WorkoutPlan" from "anon";

revoke delete on table "public"."WorkoutPlan" from "authenticated";

revoke insert on table "public"."WorkoutPlan" from "authenticated";

revoke references on table "public"."WorkoutPlan" from "authenticated";

revoke select on table "public"."WorkoutPlan" from "authenticated";

revoke trigger on table "public"."WorkoutPlan" from "authenticated";

revoke truncate on table "public"."WorkoutPlan" from "authenticated";

revoke update on table "public"."WorkoutPlan" from "authenticated";

revoke delete on table "public"."WorkoutPlan" from "service_role";

revoke insert on table "public"."WorkoutPlan" from "service_role";

revoke references on table "public"."WorkoutPlan" from "service_role";

revoke select on table "public"."WorkoutPlan" from "service_role";

revoke trigger on table "public"."WorkoutPlan" from "service_role";

revoke truncate on table "public"."WorkoutPlan" from "service_role";

revoke update on table "public"."WorkoutPlan" from "service_role";

alter table "public"."WorkoutPlan" drop constraint "WorkoutPlan_user_id_fkey";

alter table "public"."users" drop constraint "users_gender_check";

alter table "public"."users" drop constraint "users_password_key";

alter table "public"."WorkoutPlan" drop constraint "WorkoutPlan_pkey";

drop index if exists "public"."WorkoutPlan_pkey";

drop index if exists "public"."users_password_key";

drop table "public"."WorkoutPlan";


  create table "public"."equipment" (
    "id" smallint generated by default as identity not null,
    "name" text not null
      );


alter table "public"."equipment" enable row level security;


  create table "public"."exercise_muscles" (
    "exercise_id" uuid not null,
    "muscle_group_id" smallint not null,
    "role" text not null
      );


alter table "public"."exercise_muscles" enable row level security;


  create table "public"."exercise_type" (
    "id" smallint generated by default as identity not null,
    "name" text not null
      );


alter table "public"."exercise_type" enable row level security;


  create table "public"."exercises" (
    "id" uuid not null default gen_random_uuid(),
    "created_by" uuid not null,
    "name" text not null,
    "equipment_id" smallint,
    "exercise_type_id" smallint,
    "image_url" text,
    "is_public" boolean not null,
    "created_at" timestamp with time zone not null
      );


alter table "public"."exercises" enable row level security;


  create table "public"."muscle_group" (
    "id" smallint generated by default as identity not null,
    "name" text not null,
    "image_url" text
      );


alter table "public"."muscle_group" enable row level security;


  create table "public"."sets" (
    "id" uuid not null default gen_random_uuid(),
    "workout_exercise_id" uuid not null,
    "position" bigint not null,
    "weight_kg" numeric not null,
    "reps" bigint not null,
    "completed" boolean not null
      );


alter table "public"."sets" enable row level security;


  create table "public"."workout_exercise" (
    "id" uuid not null default gen_random_uuid(),
    "workout_id" uuid not null,
    "exercise_id" uuid not null,
    "position" bigint not null,
    "rest_timer_seconds" bigint not null
      );


alter table "public"."workout_exercise" enable row level security;


  create table "public"."workouts" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid not null,
    "name" text not null,
    "duration_seconds" bigint,
    "total_volume_kg" bigint,
    "total_sets" bigint,
    "started_at" timestamp with time zone not null,
    "finished_at" timestamp with time zone,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."workouts" enable row level security;

alter table "public"."users" drop column "gender";

alter table "public"."users" drop column "password";

alter table "public"."users" drop column "weight";

alter table "public"."users" add column "avatar_url" text;

alter table "public"."users" add column "created_at" timestamp with time zone not null default now();

alter table "public"."users" alter column "id" drop identity;

alter table "public"."users" alter column "id" set data type uuid using "id"::uuid;

alter table "public"."users" alter column "username" set data type text using "username"::text;

CREATE UNIQUE INDEX equipment_name_key ON public.equipment USING btree (name);

CREATE UNIQUE INDEX equipment_pkey ON public.equipment USING btree (id);

CREATE UNIQUE INDEX exercise_muscles_pkey ON public.exercise_muscles USING btree (exercise_id, muscle_group_id);

CREATE UNIQUE INDEX exercise_type_exercise_type_key ON public.exercise_type USING btree (name);

CREATE UNIQUE INDEX exercise_type_pkey ON public.exercise_type USING btree (id);

CREATE UNIQUE INDEX exercises_pkey ON public.exercises USING btree (id);

CREATE UNIQUE INDEX muscle_group_name_key ON public.muscle_group USING btree (name);

CREATE UNIQUE INDEX muscle_group_pkey ON public.muscle_group USING btree (id);

CREATE UNIQUE INDEX sets_pkey ON public.sets USING btree (id);

CREATE UNIQUE INDEX users_email_key ON public.users USING btree (email);

CREATE UNIQUE INDEX users_username_key ON public.users USING btree (username);

CREATE UNIQUE INDEX workout_exercises_pkey ON public.workout_exercise USING btree (id);

CREATE UNIQUE INDEX workouts_pkey ON public.workouts USING btree (id);

alter table "public"."equipment" add constraint "equipment_pkey" PRIMARY KEY using index "equipment_pkey";

alter table "public"."exercise_muscles" add constraint "exercise_muscles_pkey" PRIMARY KEY using index "exercise_muscles_pkey";

alter table "public"."exercise_type" add constraint "exercise_type_pkey" PRIMARY KEY using index "exercise_type_pkey";

alter table "public"."exercises" add constraint "exercises_pkey" PRIMARY KEY using index "exercises_pkey";

alter table "public"."muscle_group" add constraint "muscle_group_pkey" PRIMARY KEY using index "muscle_group_pkey";

alter table "public"."sets" add constraint "sets_pkey" PRIMARY KEY using index "sets_pkey";

alter table "public"."workout_exercise" add constraint "workout_exercises_pkey" PRIMARY KEY using index "workout_exercises_pkey";

alter table "public"."workouts" add constraint "workouts_pkey" PRIMARY KEY using index "workouts_pkey";

alter table "public"."equipment" add constraint "equipment_name_key" UNIQUE using index "equipment_name_key";

alter table "public"."exercise_muscles" add constraint "exercise_muscles_exercise_id_fkey" FOREIGN KEY (exercise_id) REFERENCES public.exercises(id) not valid;

alter table "public"."exercise_muscles" validate constraint "exercise_muscles_exercise_id_fkey";

alter table "public"."exercise_muscles" add constraint "exercise_muscles_muscle_group_id_fkey" FOREIGN KEY (muscle_group_id) REFERENCES public.muscle_group(id) not valid;

alter table "public"."exercise_muscles" validate constraint "exercise_muscles_muscle_group_id_fkey";

alter table "public"."exercise_type" add constraint "exercise_type_exercise_type_key" UNIQUE using index "exercise_type_exercise_type_key";

alter table "public"."exercises" add constraint "exercises_created_by_fkey" FOREIGN KEY (created_by) REFERENCES public.users(id) not valid;

alter table "public"."exercises" validate constraint "exercises_created_by_fkey";

alter table "public"."exercises" add constraint "exercises_equipment_id_fkey" FOREIGN KEY (equipment_id) REFERENCES public.equipment(id) not valid;

alter table "public"."exercises" validate constraint "exercises_equipment_id_fkey";

alter table "public"."exercises" add constraint "exercises_exercise_type_id_fkey" FOREIGN KEY (exercise_type_id) REFERENCES public.exercise_type(id) not valid;

alter table "public"."exercises" validate constraint "exercises_exercise_type_id_fkey";

alter table "public"."muscle_group" add constraint "muscle_group_name_key" UNIQUE using index "muscle_group_name_key";

alter table "public"."sets" add constraint "sets_workout_exercise_id_fkey" FOREIGN KEY (workout_exercise_id) REFERENCES public.workout_exercise(id) not valid;

alter table "public"."sets" validate constraint "sets_workout_exercise_id_fkey";

alter table "public"."users" add constraint "users_email_key" UNIQUE using index "users_email_key";

alter table "public"."users" add constraint "users_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) not valid;

alter table "public"."users" validate constraint "users_id_fkey";

alter table "public"."users" add constraint "users_username_key" UNIQUE using index "users_username_key";

alter table "public"."workout_exercise" add constraint "workout_exercises_exercise_id_fkey" FOREIGN KEY (exercise_id) REFERENCES public.exercises(id) not valid;

alter table "public"."workout_exercise" validate constraint "workout_exercises_exercise_id_fkey";

alter table "public"."workout_exercise" add constraint "workout_exercises_workout_id_fkey" FOREIGN KEY (workout_id) REFERENCES public.workouts(id) not valid;

alter table "public"."workout_exercise" validate constraint "workout_exercises_workout_id_fkey";

alter table "public"."workouts" add constraint "workouts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) not valid;

alter table "public"."workouts" validate constraint "workouts_user_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  INSERT INTO public.users (id, email, created_at)
  VALUES (
    NEW.id,
    NEW.email,
    NOW()
  );
  RETURN NEW;
END;
$function$
;

grant delete on table "public"."equipment" to "anon";

grant insert on table "public"."equipment" to "anon";

grant references on table "public"."equipment" to "anon";

grant select on table "public"."equipment" to "anon";

grant trigger on table "public"."equipment" to "anon";

grant truncate on table "public"."equipment" to "anon";

grant update on table "public"."equipment" to "anon";

grant delete on table "public"."equipment" to "authenticated";

grant insert on table "public"."equipment" to "authenticated";

grant references on table "public"."equipment" to "authenticated";

grant select on table "public"."equipment" to "authenticated";

grant trigger on table "public"."equipment" to "authenticated";

grant truncate on table "public"."equipment" to "authenticated";

grant update on table "public"."equipment" to "authenticated";

grant delete on table "public"."equipment" to "service_role";

grant insert on table "public"."equipment" to "service_role";

grant references on table "public"."equipment" to "service_role";

grant select on table "public"."equipment" to "service_role";

grant trigger on table "public"."equipment" to "service_role";

grant truncate on table "public"."equipment" to "service_role";

grant update on table "public"."equipment" to "service_role";

grant delete on table "public"."exercise_muscles" to "anon";

grant insert on table "public"."exercise_muscles" to "anon";

grant references on table "public"."exercise_muscles" to "anon";

grant select on table "public"."exercise_muscles" to "anon";

grant trigger on table "public"."exercise_muscles" to "anon";

grant truncate on table "public"."exercise_muscles" to "anon";

grant update on table "public"."exercise_muscles" to "anon";

grant delete on table "public"."exercise_muscles" to "authenticated";

grant insert on table "public"."exercise_muscles" to "authenticated";

grant references on table "public"."exercise_muscles" to "authenticated";

grant select on table "public"."exercise_muscles" to "authenticated";

grant trigger on table "public"."exercise_muscles" to "authenticated";

grant truncate on table "public"."exercise_muscles" to "authenticated";

grant update on table "public"."exercise_muscles" to "authenticated";

grant delete on table "public"."exercise_muscles" to "service_role";

grant insert on table "public"."exercise_muscles" to "service_role";

grant references on table "public"."exercise_muscles" to "service_role";

grant select on table "public"."exercise_muscles" to "service_role";

grant trigger on table "public"."exercise_muscles" to "service_role";

grant truncate on table "public"."exercise_muscles" to "service_role";

grant update on table "public"."exercise_muscles" to "service_role";

grant delete on table "public"."exercise_type" to "anon";

grant insert on table "public"."exercise_type" to "anon";

grant references on table "public"."exercise_type" to "anon";

grant select on table "public"."exercise_type" to "anon";

grant trigger on table "public"."exercise_type" to "anon";

grant truncate on table "public"."exercise_type" to "anon";

grant update on table "public"."exercise_type" to "anon";

grant delete on table "public"."exercise_type" to "authenticated";

grant insert on table "public"."exercise_type" to "authenticated";

grant references on table "public"."exercise_type" to "authenticated";

grant select on table "public"."exercise_type" to "authenticated";

grant trigger on table "public"."exercise_type" to "authenticated";

grant truncate on table "public"."exercise_type" to "authenticated";

grant update on table "public"."exercise_type" to "authenticated";

grant delete on table "public"."exercise_type" to "service_role";

grant insert on table "public"."exercise_type" to "service_role";

grant references on table "public"."exercise_type" to "service_role";

grant select on table "public"."exercise_type" to "service_role";

grant trigger on table "public"."exercise_type" to "service_role";

grant truncate on table "public"."exercise_type" to "service_role";

grant update on table "public"."exercise_type" to "service_role";

grant delete on table "public"."exercises" to "anon";

grant insert on table "public"."exercises" to "anon";

grant references on table "public"."exercises" to "anon";

grant select on table "public"."exercises" to "anon";

grant trigger on table "public"."exercises" to "anon";

grant truncate on table "public"."exercises" to "anon";

grant update on table "public"."exercises" to "anon";

grant delete on table "public"."exercises" to "authenticated";

grant insert on table "public"."exercises" to "authenticated";

grant references on table "public"."exercises" to "authenticated";

grant select on table "public"."exercises" to "authenticated";

grant trigger on table "public"."exercises" to "authenticated";

grant truncate on table "public"."exercises" to "authenticated";

grant update on table "public"."exercises" to "authenticated";

grant delete on table "public"."exercises" to "service_role";

grant insert on table "public"."exercises" to "service_role";

grant references on table "public"."exercises" to "service_role";

grant select on table "public"."exercises" to "service_role";

grant trigger on table "public"."exercises" to "service_role";

grant truncate on table "public"."exercises" to "service_role";

grant update on table "public"."exercises" to "service_role";

grant delete on table "public"."muscle_group" to "anon";

grant insert on table "public"."muscle_group" to "anon";

grant references on table "public"."muscle_group" to "anon";

grant select on table "public"."muscle_group" to "anon";

grant trigger on table "public"."muscle_group" to "anon";

grant truncate on table "public"."muscle_group" to "anon";

grant update on table "public"."muscle_group" to "anon";

grant delete on table "public"."muscle_group" to "authenticated";

grant insert on table "public"."muscle_group" to "authenticated";

grant references on table "public"."muscle_group" to "authenticated";

grant select on table "public"."muscle_group" to "authenticated";

grant trigger on table "public"."muscle_group" to "authenticated";

grant truncate on table "public"."muscle_group" to "authenticated";

grant update on table "public"."muscle_group" to "authenticated";

grant delete on table "public"."muscle_group" to "service_role";

grant insert on table "public"."muscle_group" to "service_role";

grant references on table "public"."muscle_group" to "service_role";

grant select on table "public"."muscle_group" to "service_role";

grant trigger on table "public"."muscle_group" to "service_role";

grant truncate on table "public"."muscle_group" to "service_role";

grant update on table "public"."muscle_group" to "service_role";

grant delete on table "public"."sets" to "anon";

grant insert on table "public"."sets" to "anon";

grant references on table "public"."sets" to "anon";

grant select on table "public"."sets" to "anon";

grant trigger on table "public"."sets" to "anon";

grant truncate on table "public"."sets" to "anon";

grant update on table "public"."sets" to "anon";

grant delete on table "public"."sets" to "authenticated";

grant insert on table "public"."sets" to "authenticated";

grant references on table "public"."sets" to "authenticated";

grant select on table "public"."sets" to "authenticated";

grant trigger on table "public"."sets" to "authenticated";

grant truncate on table "public"."sets" to "authenticated";

grant update on table "public"."sets" to "authenticated";

grant delete on table "public"."sets" to "service_role";

grant insert on table "public"."sets" to "service_role";

grant references on table "public"."sets" to "service_role";

grant select on table "public"."sets" to "service_role";

grant trigger on table "public"."sets" to "service_role";

grant truncate on table "public"."sets" to "service_role";

grant update on table "public"."sets" to "service_role";

grant delete on table "public"."workout_exercise" to "anon";

grant insert on table "public"."workout_exercise" to "anon";

grant references on table "public"."workout_exercise" to "anon";

grant select on table "public"."workout_exercise" to "anon";

grant trigger on table "public"."workout_exercise" to "anon";

grant truncate on table "public"."workout_exercise" to "anon";

grant update on table "public"."workout_exercise" to "anon";

grant delete on table "public"."workout_exercise" to "authenticated";

grant insert on table "public"."workout_exercise" to "authenticated";

grant references on table "public"."workout_exercise" to "authenticated";

grant select on table "public"."workout_exercise" to "authenticated";

grant trigger on table "public"."workout_exercise" to "authenticated";

grant truncate on table "public"."workout_exercise" to "authenticated";

grant update on table "public"."workout_exercise" to "authenticated";

grant delete on table "public"."workout_exercise" to "service_role";

grant insert on table "public"."workout_exercise" to "service_role";

grant references on table "public"."workout_exercise" to "service_role";

grant select on table "public"."workout_exercise" to "service_role";

grant trigger on table "public"."workout_exercise" to "service_role";

grant truncate on table "public"."workout_exercise" to "service_role";

grant update on table "public"."workout_exercise" to "service_role";

grant delete on table "public"."workouts" to "anon";

grant insert on table "public"."workouts" to "anon";

grant references on table "public"."workouts" to "anon";

grant select on table "public"."workouts" to "anon";

grant trigger on table "public"."workouts" to "anon";

grant truncate on table "public"."workouts" to "anon";

grant update on table "public"."workouts" to "anon";

grant delete on table "public"."workouts" to "authenticated";

grant insert on table "public"."workouts" to "authenticated";

grant references on table "public"."workouts" to "authenticated";

grant select on table "public"."workouts" to "authenticated";

grant trigger on table "public"."workouts" to "authenticated";

grant truncate on table "public"."workouts" to "authenticated";

grant update on table "public"."workouts" to "authenticated";

grant delete on table "public"."workouts" to "service_role";

grant insert on table "public"."workouts" to "service_role";

grant references on table "public"."workouts" to "service_role";

grant select on table "public"."workouts" to "service_role";

grant trigger on table "public"."workouts" to "service_role";

grant truncate on table "public"."workouts" to "service_role";

grant update on table "public"."workouts" to "service_role";


  create policy "equipment: public read"
  on "public"."equipment"
  as permissive
  for select
  to public
using (true);



  create policy "exercise_muscles: delete own"
  on "public"."exercise_muscles"
  as permissive
  for delete
  to public
using ((EXISTS ( SELECT 1
   FROM public.exercises e
  WHERE ((e.id = exercise_muscles.exercise_id) AND (e.created_by = auth.uid())))));



  create policy "exercise_muscles: insert own"
  on "public"."exercise_muscles"
  as permissive
  for insert
  to public
with check ((EXISTS ( SELECT 1
   FROM public.exercises e
  WHERE ((e.id = exercise_muscles.exercise_id) AND (e.created_by = auth.uid())))));



  create policy "exercise_muscles: select"
  on "public"."exercise_muscles"
  as permissive
  for select
  to public
using ((EXISTS ( SELECT 1
   FROM public.exercises e
  WHERE ((e.id = exercise_muscles.exercise_id) AND ((e.created_by = auth.uid()) OR (e.is_public = true))))));



  create policy "exercise_type: public read"
  on "public"."exercise_type"
  as permissive
  for select
  to public
using (true);



  create policy "exercises: delete own"
  on "public"."exercises"
  as permissive
  for delete
  to public
using ((auth.uid() = created_by));



  create policy "exercises: insert own"
  on "public"."exercises"
  as permissive
  for insert
  to public
with check ((auth.uid() = created_by));



  create policy "exercises: select own or public"
  on "public"."exercises"
  as permissive
  for select
  to public
using (((auth.uid() = created_by) OR (is_public = true)));



  create policy "exercises: update own"
  on "public"."exercises"
  as permissive
  for update
  to public
using ((auth.uid() = created_by));



  create policy "muscle_group: public read"
  on "public"."muscle_group"
  as permissive
  for select
  to public
using (true);



  create policy "sets: delete own"
  on "public"."sets"
  as permissive
  for delete
  to public
using ((EXISTS ( SELECT 1
   FROM (public.workout_exercise we
     JOIN public.workouts w ON ((w.id = we.workout_id)))
  WHERE ((we.id = sets.workout_exercise_id) AND (w.user_id = auth.uid())))));



  create policy "sets: insert own"
  on "public"."sets"
  as permissive
  for insert
  to public
with check ((EXISTS ( SELECT 1
   FROM (public.workout_exercise we
     JOIN public.workouts w ON ((w.id = we.workout_id)))
  WHERE ((we.id = sets.workout_exercise_id) AND (w.user_id = auth.uid())))));



  create policy "sets: select own"
  on "public"."sets"
  as permissive
  for select
  to public
using ((EXISTS ( SELECT 1
   FROM (public.workout_exercise we
     JOIN public.workouts w ON ((w.id = we.workout_id)))
  WHERE ((we.id = sets.workout_exercise_id) AND (w.user_id = auth.uid())))));



  create policy "users: select own"
  on "public"."users"
  as permissive
  for select
  to public
using ((auth.uid() = id));



  create policy "users: update own"
  on "public"."users"
  as permissive
  for update
  to public
using ((auth.uid() = id));



  create policy "workout_exercise: delete own"
  on "public"."workout_exercise"
  as permissive
  for delete
  to public
using ((EXISTS ( SELECT 1
   FROM public.workouts w
  WHERE ((w.id = workout_exercise.workout_id) AND (w.user_id = auth.uid())))));



  create policy "workout_exercise: insert own"
  on "public"."workout_exercise"
  as permissive
  for insert
  to public
with check ((EXISTS ( SELECT 1
   FROM public.workouts w
  WHERE ((w.id = workout_exercise.workout_id) AND (w.user_id = auth.uid())))));



  create policy "workout_exercise: select own"
  on "public"."workout_exercise"
  as permissive
  for select
  to public
using ((EXISTS ( SELECT 1
   FROM public.workouts w
  WHERE ((w.id = workout_exercise.workout_id) AND (w.user_id = auth.uid())))));



  create policy "workouts: delete own"
  on "public"."workouts"
  as permissive
  for delete
  to public
using ((auth.uid() = user_id));



  create policy "workouts: insert own"
  on "public"."workouts"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));



  create policy "workouts: select own"
  on "public"."workouts"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "workouts: update own"
  on "public"."workouts"
  as permissive
  for update
  to public
using ((auth.uid() = user_id));


CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


